#pragma once

namespace Chilli
{
	enum class ImageType
	{
		IMAGE_TYPE_1D,
		IMAGE_TYPE_2D,
		IMAGE_TYPE_3D,
	};

	enum class ImageFormat
	{
		RGBA8, D32, D24_S8, D32_S8
	};

	enum ImageUsage : uint32_t {
		IMAGE_USAGE_NONE = 0,
		IMAGE_USAGE_SAMPLED_IMAGE = 1 << 0,
		IMAGE_USAGE_COLOR_ATTACHMENT = 1 << 1,
		IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT = 1 << 2,
		IMAGE_USAGE_STORAGE_IMAGE = 1 << 3,
		IMAGE_USAGE_TRANSFER_SRC = 1 << 4,
		IMAGE_USAGE_TRANSFER_DST = 1 << 5,
		IMAGE_USAGE_INPUT_ATTACHMENT = 1 << 6,
		IMAGE_USAGE_PRESENT_IMAGE = 1 << 7
	};

}
